<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Jadwal_model extends CI_Model
{

    public $table = 'jadwal';
    public $id = 'id_jadwal';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    //get field
    function get_field(){
      return $this->db->list_fields($this->table);
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }


    function getJoin(){
      $sql="SELECT * FROM `jadwal` INNER JOIN `studio` ON `jadwal`.`id_studio`=`studio`.`id_studio` INNER JOIN `film` ON `jadwal`.`id_film`=`film`.`id_film` INNER JOIN `jam_tayang` ON `jadwal`.`id_jam_tayang`=`jam_tayang`.`id_jam_tayang`";
      return $this->db->query($sql);
    }

    function getJamFilm($id_film,$id_studio){
      $sql="SELECT *
      FROM `jadwal`  INNER JOIN `studio` ON `jadwal`.`id_studio`=`studio`.`id_studio`
      INNER JOIN `film` ON `jadwal`.`id_film`=`film`.`id_film`
      INNER JOIN `jam_tayang` ON `jadwal`.`id_jam_tayang`=`jam_tayang`.`id_jam_tayang`
      WHERE `jadwal`.`id_film`='$id_film' and `jadwal`.`id_studio`='$id_studio'";
      return $this->db->query($sql);
    }

    function getJudulFilm(){//ambil film yang didalam rentang waktu tanggal selesai dengan tanggal mulai
      $sql="SELECT distinct `jadwal`.`id_film`,`film`.`judul_film`,`film`.`tanggal_selesai`,`film`.`tanggal_mulai`,DATEDIFF(`film`.`tanggal_selesai`,`film`.`tanggal_mulai`) as Hari,DATEDIFF(`film`.`tanggal_selesai`,NOW()) as DurasiHari,`film`.`url_gambar` FROM `jadwal`
      INNER JOIN `studio` ON `jadwal`.`id_studio`=`studio`.`id_studio`
      INNER JOIN `film` ON `jadwal`.`id_film`=`film`.`id_film`
      INNER JOIN `jam_tayang` ON `jadwal`.`id_jam_tayang`=`jam_tayang`.`id_jam_tayang`
      WHERE DATEDIFF(`film`.`tanggal_selesai`,NOW()) >0";
      return $this->db->query($sql);
    }

    function getJudulFilmbyId($id_film){
      $sql="SELECT distinct `jadwal`.`id_film`,`film`.`judul_film`,`film`.`tanggal_selesai`,`film`.`tanggal_mulai`,DATEDIFF(`film`.`tanggal_selesai`,`film`.`tanggal_mulai`) as Hari,DATEDIFF(`film`.`tanggal_selesai`,NOW()) as DurasiHari FROM `jadwal`
      INNER JOIN `studio` ON `jadwal`.`id_studio`=`studio`.`id_studio`
      INNER JOIN `film` ON `jadwal`.`id_film`=`film`.`id_film`
      INNER JOIN `jam_tayang` ON `jadwal`.`id_jam_tayang`=`jam_tayang`.`id_jam_tayang`
      WHERE DATEDIFF(`film`.`tanggal_selesai`,NOW()) >0 AND `jadwal`.`id_film`='$id_film'";
      return $this->db->query($sql);
    }

    function getStudiobyFilm($id_film){
      $sql="SELECT distinct `jadwal`.`id_studio`,`nama_studio`
      FROM `jadwal`
      INNER JOIN `studio` ON `jadwal`.`id_studio`=`studio`.`id_studio`
      INNER JOIN `film` ON `jadwal`.`id_film`=`film`.`id_film`
      INNER JOIN `jam_tayang` ON `jadwal`.`id_jam_tayang`=`jam_tayang`.`id_jam_tayang`
      WHERE `jadwal`.`id_film`='$id_film'";
      return $this->db->query($sql);
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_jadwal', $q);
	$this->db->or_like('id_studio', $q);
	$this->db->or_like('id_film', $q);
	$this->db->or_like('id_jam_tayang', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_jadwal', $q);
	$this->db->or_like('id_studio', $q);
	$this->db->or_like('id_film', $q);
	$this->db->or_like('id_jam_tayang', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Jadwal_model.php */
/* Location: ./application/models/Jadwal_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-19 09:12:59 */
/* http://harviacode.com */
